<?php
if (!defined('ABSPATH')) {
    exit;
}

return [
    ['group' => 'Attention Seekers', 'class' => 'animate__bounce', 'label' => 'Bounce', 'description' => 'Bounces the element up and down to attract attention.'],
    ['group' => 'Attention Seekers', 'class' => 'animate__flash', 'label' => 'Flash', 'description' => 'Quickly flashes the element by alternating opacity.'],
    ['group' => 'Attention Seekers', 'class' => 'animate__pulse', 'label' => 'Pulse', 'description' => 'Gently scales the element in and out.'],
    ['group' => 'Attention Seekers', 'class' => 'animate__rubberBand', 'label' => 'Rubber Band', 'description' => 'Stretches and snaps the element back into place.'],
    ['group' => 'Attention Seekers', 'class' => 'animate__shakeX', 'label' => 'Shake X', 'description' => 'Shakes the element horizontally.'],
    ['group' => 'Attention Seekers', 'class' => 'animate__shakeY', 'label' => 'Shake Y', 'description' => 'Shakes the element vertically.'],
    ['group' => 'Attention Seekers', 'class' => 'animate__headShake', 'label' => 'Head Shake', 'description' => 'A playful horizontal shake with slight rotation.'],
    ['group' => 'Attention Seekers', 'class' => 'animate__swing', 'label' => 'Swing', 'description' => 'Swings the element from side to side.'],
    ['group' => 'Attention Seekers', 'class' => 'animate__tada', 'label' => 'Tada', 'description' => 'Adds a celebratory scale and rotate effect.'],
    ['group' => 'Attention Seekers', 'class' => 'animate__wobble', 'label' => 'Wobble', 'description' => 'Moves the element in a loose side-to-side wobble.'],
    ['group' => 'Attention Seekers', 'class' => 'animate__jello', 'label' => 'Jello', 'description' => 'Creates a gelatin-like wobble distortion.'],
    ['group' => 'Back Entrances', 'class' => 'animate__backInDown', 'label' => 'Back In Down', 'description' => 'Enters from above with slight scale overshoot.'],
    ['group' => 'Back Entrances', 'class' => 'animate__backInLeft', 'label' => 'Back In Left', 'description' => 'Enters from the left with depth.'],
    ['group' => 'Back Entrances', 'class' => 'animate__backInRight', 'label' => 'Back In Right', 'description' => 'Enters from the right with depth.'],
    ['group' => 'Back Entrances', 'class' => 'animate__backInUp', 'label' => 'Back In Up', 'description' => 'Enters from below with depth.'],
    ['group' => 'Back Exits', 'class' => 'animate__backOutDown', 'label' => 'Back Out Down', 'description' => 'Exits downward with depth.'],
    ['group' => 'Back Exits', 'class' => 'animate__backOutLeft', 'label' => 'Back Out Left', 'description' => 'Exits left with depth.'],
    ['group' => 'Back Exits', 'class' => 'animate__backOutRight', 'label' => 'Back Out Right', 'description' => 'Exits right with depth.'],
    ['group' => 'Back Exits', 'class' => 'animate__backOutUp', 'label' => 'Back Out Up', 'description' => 'Exits upward with depth.'],
    ['group' => 'Bouncing Entrances', 'class' => 'animate__bounceIn', 'label' => 'Bounce In', 'description' => 'Bounces into view from scale 0.'],
    ['group' => 'Bouncing Entrances', 'class' => 'animate__bounceInDown', 'label' => 'Bounce In Down', 'description' => 'Drops in with a bounce.'],
    ['group' => 'Bouncing Entrances', 'class' => 'animate__bounceInLeft', 'label' => 'Bounce In Left', 'description' => 'Bounces in from the left.'],
    ['group' => 'Bouncing Entrances', 'class' => 'animate__bounceInRight', 'label' => 'Bounce In Right', 'description' => 'Bounces in from the right.'],
    ['group' => 'Bouncing Entrances', 'class' => 'animate__bounceInUp', 'label' => 'Bounce In Up', 'description' => 'Bounces in from the bottom.'],
    ['group' => 'Bouncing Exits', 'class' => 'animate__bounceOut', 'label' => 'Bounce Out', 'description' => 'Shrinks away with a bounce.'],
    ['group' => 'Bouncing Exits', 'class' => 'animate__bounceOutDown', 'label' => 'Bounce Out Down', 'description' => 'Exits downward with bounce.'],
    ['group' => 'Bouncing Exits', 'class' => 'animate__bounceOutLeft', 'label' => 'Bounce Out Left', 'description' => 'Exits left with bounce.'],
    ['group' => 'Bouncing Exits', 'class' => 'animate__bounceOutRight', 'label' => 'Bounce Out Right', 'description' => 'Exits right with bounce.'],
    ['group' => 'Bouncing Exits', 'class' => 'animate__bounceOutUp', 'label' => 'Bounce Out Up', 'description' => 'Exits upward with bounce.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeIn', 'label' => 'Fade In', 'description' => 'Smoothly fades the element into view.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeInDown', 'label' => 'Fade In Down', 'description' => 'Fades in while moving downward.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeInDownBig', 'label' => 'Fade In Down Big', 'description' => 'Fades in from far above.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeInLeft', 'label' => 'Fade In Left', 'description' => 'Fades in while moving from the left.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeInLeftBig', 'label' => 'Fade In Left Big', 'description' => 'Fades in from far left.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeInRight', 'label' => 'Fade In Right', 'description' => 'Fades in while moving from the right.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeInRightBig', 'label' => 'Fade In Right Big', 'description' => 'Fades in from far right.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeInUp', 'label' => 'Fade In Up', 'description' => 'Fades in while moving upward.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeInUpBig', 'label' => 'Fade In Up Big', 'description' => 'Fades in from far below.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeInTopLeft', 'label' => 'Fade In Top Left', 'description' => 'Fades in from the top-left corner.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeInTopRight', 'label' => 'Fade In Top Right', 'description' => 'Fades in from the top-right corner.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeInBottomLeft', 'label' => 'Fade In Bottom Left', 'description' => 'Fades in from the bottom-left corner.'],
    ['group' => 'Fading Entrances', 'class' => 'animate__fadeInBottomRight', 'label' => 'Fade In Bottom Right', 'description' => 'Fades in from the bottom-right corner.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOut', 'label' => 'Fade Out', 'description' => 'Smoothly fades the element away.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOutDown', 'label' => 'Fade Out Down', 'description' => 'Fades out while moving downward.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOutDownBig', 'label' => 'Fade Out Down Big', 'description' => 'Fades out far downward.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOutLeft', 'label' => 'Fade Out Left', 'description' => 'Fades out while moving left.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOutLeftBig', 'label' => 'Fade Out Left Big', 'description' => 'Fades out far left.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOutRight', 'label' => 'Fade Out Right', 'description' => 'Fades out while moving right.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOutRightBig', 'label' => 'Fade Out Right Big', 'description' => 'Fades out far right.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOutUp', 'label' => 'Fade Out Up', 'description' => 'Fades out while moving upward.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOutUpBig', 'label' => 'Fade Out Up Big', 'description' => 'Fades out far upward.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOutTopLeft', 'label' => 'Fade Out Top Left', 'description' => 'Fades out toward the top-left corner.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOutTopRight', 'label' => 'Fade Out Top Right', 'description' => 'Fades out toward the top-right corner.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOutBottomLeft', 'label' => 'Fade Out Bottom Left', 'description' => 'Fades out toward the bottom-left corner.'],
    ['group' => 'Fading Exits', 'class' => 'animate__fadeOutBottomRight', 'label' => 'Fade Out Bottom Right', 'description' => 'Fades out toward the bottom-right corner.'],
    ['group' => 'Flippers', 'class' => 'animate__flip', 'label' => 'Flip', 'description' => 'Rotates the element in 3D.'],
    ['group' => 'Flippers', 'class' => 'animate__flipInX', 'label' => 'Flip In X', 'description' => 'Flips in on the X axis.'],
    ['group' => 'Flippers', 'class' => 'animate__flipInY', 'label' => 'Flip In Y', 'description' => 'Flips in on the Y axis.'],
    ['group' => 'Flippers', 'class' => 'animate__flipOutX', 'label' => 'Flip Out X', 'description' => 'Flips out on the X axis.'],
    ['group' => 'Flippers', 'class' => 'animate__flipOutY', 'label' => 'Flip Out Y', 'description' => 'Flips out on the Y axis.'],
    ['group' => 'Lightspeed', 'class' => 'animate__lightSpeedInRight', 'label' => 'LightSpeed In Right', 'description' => 'Slides in quickly from the right with skew.'],
    ['group' => 'Lightspeed', 'class' => 'animate__lightSpeedInLeft', 'label' => 'LightSpeed In Left', 'description' => 'Slides in quickly from the left with skew.'],
    ['group' => 'Lightspeed', 'class' => 'animate__lightSpeedOutRight', 'label' => 'LightSpeed Out Right', 'description' => 'Shoots out to the right with skew.'],
    ['group' => 'Lightspeed', 'class' => 'animate__lightSpeedOutLeft', 'label' => 'LightSpeed Out Left', 'description' => 'Shoots out to the left with skew.'],
    ['group' => 'Rotating Entrances', 'class' => 'animate__rotateIn', 'label' => 'Rotate In', 'description' => 'Rotates the element into view.'],
    ['group' => 'Rotating Entrances', 'class' => 'animate__rotateInDownLeft', 'label' => 'Rotate In Down Left', 'description' => 'Rotates in from bottom-left pivot.'],
    ['group' => 'Rotating Entrances', 'class' => 'animate__rotateInDownRight', 'label' => 'Rotate In Down Right', 'description' => 'Rotates in from bottom-right pivot.'],
    ['group' => 'Rotating Entrances', 'class' => 'animate__rotateInUpLeft', 'label' => 'Rotate In Up Left', 'description' => 'Rotates in from top-left pivot.'],
    ['group' => 'Rotating Entrances', 'class' => 'animate__rotateInUpRight', 'label' => 'Rotate In Up Right', 'description' => 'Rotates in from top-right pivot.'],
    ['group' => 'Rotating Exits', 'class' => 'animate__rotateOut', 'label' => 'Rotate Out', 'description' => 'Rotates the element out of view.'],
    ['group' => 'Rotating Exits', 'class' => 'animate__rotateOutDownLeft', 'label' => 'Rotate Out Down Left', 'description' => 'Rotates out toward the bottom-left.'],
    ['group' => 'Rotating Exits', 'class' => 'animate__rotateOutDownRight', 'label' => 'Rotate Out Down Right', 'description' => 'Rotates out toward the bottom-right.'],
    ['group' => 'Rotating Exits', 'class' => 'animate__rotateOutUpLeft', 'label' => 'Rotate Out Up Left', 'description' => 'Rotates out toward the top-left.'],
    ['group' => 'Rotating Exits', 'class' => 'animate__rotateOutUpRight', 'label' => 'Rotate Out Up Right', 'description' => 'Rotates out toward the top-right.'],
    ['group' => 'Specials', 'class' => 'animate__hinge', 'label' => 'Hinge', 'description' => 'Swings from the top-left then falls away.'],
    ['group' => 'Specials', 'class' => 'animate__jackInTheBox', 'label' => 'Jack In The Box', 'description' => 'Pops in with rotation and scale.'],
    ['group' => 'Specials', 'class' => 'animate__rollIn', 'label' => 'Roll In', 'description' => 'Rolls in from the left.'],
    ['group' => 'Specials', 'class' => 'animate__rollOut', 'label' => 'Roll Out', 'description' => 'Rolls out to the right.'],
    ['group' => 'Zoom Entrances', 'class' => 'animate__zoomIn', 'label' => 'Zoom In', 'description' => 'Scales into view.'],
    ['group' => 'Zoom Entrances', 'class' => 'animate__zoomInDown', 'label' => 'Zoom In Down', 'description' => 'Zooms in from above.'],
    ['group' => 'Zoom Entrances', 'class' => 'animate__zoomInLeft', 'label' => 'Zoom In Left', 'description' => 'Zooms in from the left.'],
    ['group' => 'Zoom Entrances', 'class' => 'animate__zoomInRight', 'label' => 'Zoom In Right', 'description' => 'Zooms in from the right.'],
    ['group' => 'Zoom Entrances', 'class' => 'animate__zoomInUp', 'label' => 'Zoom In Up', 'description' => 'Zooms in from below.'],
    ['group' => 'Zoom Exits', 'class' => 'animate__zoomOut', 'label' => 'Zoom Out', 'description' => 'Scales away from view.'],
    ['group' => 'Zoom Exits', 'class' => 'animate__zoomOutDown', 'label' => 'Zoom Out Down', 'description' => 'Zooms out toward the bottom.'],
    ['group' => 'Zoom Exits', 'class' => 'animate__zoomOutLeft', 'label' => 'Zoom Out Left', 'description' => 'Zooms out toward the left.'],
    ['group' => 'Zoom Exits', 'class' => 'animate__zoomOutRight', 'label' => 'Zoom Out Right', 'description' => 'Zooms out toward the right.'],
    ['group' => 'Zoom Exits', 'class' => 'animate__zoomOutUp', 'label' => 'Zoom Out Up', 'description' => 'Zooms out toward the top.'],
    ['group' => 'Sliding Entrances', 'class' => 'animate__slideInDown', 'label' => 'Slide In Down', 'description' => 'Slides in from the top.'],
    ['group' => 'Sliding Entrances', 'class' => 'animate__slideInLeft', 'label' => 'Slide In Left', 'description' => 'Slides in from the left.'],
    ['group' => 'Sliding Entrances', 'class' => 'animate__slideInRight', 'label' => 'Slide In Right', 'description' => 'Slides in from the right.'],
    ['group' => 'Sliding Entrances', 'class' => 'animate__slideInUp', 'label' => 'Slide In Up', 'description' => 'Slides in from the bottom.'],
    ['group' => 'Sliding Exits', 'class' => 'animate__slideOutDown', 'label' => 'Slide Out Down', 'description' => 'Slides out toward the bottom.'],
    ['group' => 'Sliding Exits', 'class' => 'animate__slideOutLeft', 'label' => 'Slide Out Left', 'description' => 'Slides out toward the left.'],
    ['group' => 'Sliding Exits', 'class' => 'animate__slideOutRight', 'label' => 'Slide Out Right', 'description' => 'Slides out toward the right.'],
    ['group' => 'Sliding Exits', 'class' => 'animate__slideOutUp', 'label' => 'Slide Out Up', 'description' => 'Slides out toward the top.'],
];
